openspec: 1.0.8
name: OpenApi
version: 3.0.1

# @todo specify required fields

spec:
  type: object
  fields:

    openapi:
      type: string

    info:
      type: ref
      spec: ApiInfo

    servers:
      type: array
      items:
        type: ref
        spec: Server

    paths:
      type: ref
      spec: Paths

    components:
      type: ref
      spec: Components

    security:
      type: array
      items:
        type: ref
        spec: SecurityRequirement

    tags:
      type: array
      items:
        type: ref
        spec: Tag

    externalDocs:
      type: ref
      spec: ExternalDocumentation

  extensible: true
  extensionFieldNamesPattern: ^x-

definitions:

  ApiInfo:
    type: object
    fields:
      title:
        type: string
      description:
        type: string
      termsOfService:
        type: string
      contact:
        type: ref
        spec: Contact
      license:
        type: ref
        spec: License
      version:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  Contact:
    type: object
    fields:
      name:
        type: string
      url:
        type: string
      email:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  License:
    type: object
    fields:
      name:
        type: string
      url:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  Server:
    type: object
    fields:
      url:
        type: string
      description:
        type: string
      variables:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: ServerVariable
    extensible: true
    extensionFieldNamesPattern: ^x-

  ServerVariable:
    type: object
    fields:
      enum:
        type: array
        items:
          type: string
      default:
        type: string
      description:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  Paths:
    type: object
    extensible: true
    extensionFields:
      type: ref
      spec: PathItem
    # @todo Implement ^x- fields for this spec

  PathItem:
    type: object
    fields:
      $ref:
        type: string
      summary:
        type: string
      description:
        type: string
      get:
        type: ref
        spec: Operation
      put:
        type: ref
        spec: Operation
      post:
        type: ref
        spec: Operation
      delete:
        type: ref
        spec: Operation
      options:
        type: ref
        spec: Operation
      head:
        type: ref
        spec: Operation
      patch:
        type: ref
        spec: Operation
      trace:
        type: ref
        spec: Operation
      servers:
        type: array
        items:
          type: ref
          spec: Server
      parameters:
        type: array
        items:
          type: mixed
          options:
            - type: ref
              spec: Parameter
            - type: ref
              spec: Reference
    extensible: true
    extensionFieldNamesPattern: ^x-

  Operation:
    type: object
    fields:
      tags:
        type: array
        items:
          type: string
      summary:
        type: string
      description:
        type: string
      externalDocs:
        type: ref
        spec: ExternalDocumentation
      operationId:
        type: string
      parameters:
        type: array
        items:
          type: mixed
          options:
            - type: ref
              spec: Parameter
            - type: ref
              spec: Reference
      requestBody:
        type: mixed
        options:
          - type: ref
            spec: RequestBody
          - type: ref
            spec: Reference
      responses:
        type: ref
        spec: Responses
      callbacks:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Callback
            - type: ref
              spec: Reference
      deprecated:
        type: boolean
      security:
        type: array
        items:
          type: ref
          spec: SecurityRequirement
      servers:
        type: array
        items:
          type: ref
          spec: Server
    extensible: true
    extensionFieldNamesPattern: ^x-

  Parameter:
    type: object
    fields:
      name:
        type: string
      in:
        type: string
      description:
        type: string
      required:
        type: boolean
      deprecated:
        type: boolean
      allowEmptyValue:
        type: boolean
      style:
        type: string
      explode:
        type: boolean
      allowReserved:
        type: boolean
      schema:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      example:
        type: ref
        spec: Any
      examples:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Example
            - type: ref
              spec: Reference
      content:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: MediaType
    extensible: true
    extensionFieldNamesPattern: ^x-

  Reference:
    type: object
    fields:
      $ref:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  ExternalDocumentation:
    type: object
    fields:
      description:
        type: string
      url:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  Callback:
    # @todo Implement ^x- fields for this spec
    type: object
    extensible: true
    extensionFields:
      type: ref
      spec: PathItem

  RequestBody:
    type: object
    fields:
      description:
        type: string
      content:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: MediaType
      required:
        type: boolean

  MediaType:
    type: object
    fields:
      schema:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      example:
        type: ref
        spec: Any
      examples:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Example
            - type: ref
              spec: Reference
      encoding:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: Encoding
    extensible: true
    extensionFieldNamesPattern: ^x-

  Schema:
    type: object
    fields:
      title:
        type: string
      multipleOf:
        type: ref
        spec: Number
      maximum:
        type: ref
        spec: Number
      exclusiveMaximum:
        type: boolean
      minimum:
        type: ref
        spec: Number
      exclusiveMinimum:
        type: boolean
      maxLength:
        type: integer
      minLength:
        type: integer
      pattern:
        type: string
      maxItems:
        type: integer
      minItems:
        type: integer
      uniqueItems:
        type: boolean
      maxProperties:
        type: integer
      minProperties:
        type: integer
      required:
        type: array
        items:
          type: string
      enum:
        type: array
        items:
          type: ref
          spec: Any
      type:
        type: string
      allOf:
        type: array
        items:
          type: mixed
          options:
            - type: ref
              spec: Schema
            - type: ref
              spec: Reference
      oneOf:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      anyOf:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      not:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      items:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      properties:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Schema
            - type: ref
              spec: Reference
      additionalProperties:
        type: mixed
        options:
          - type: boolean
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      description:
        type: string
      format:
        type: string
      default:
        type: ref
        spec: Any
      nullable:
        type: boolean
      discriminator:
        type: ref
        spec: Discriminator
      readOnly:
        type: boolean
      writeOnly:
        type: boolean
      xml:
        type: ref
        spec: XmlObject
      externalDocs:
        type: ref
        spec: ExternalDocumentation
      example:
        type: ref
        spec: Any
      deprecated:
        type: boolean
    extensible: true
    extensionFieldNamesPattern: ^x-

  Number:
    type: mixed
    options:
      - type: integer
      - type: float

  Any:
    type: mixed
    options:
      - type: 'null'
      - type: boolean
      - type: string
      - type: integer
      - type: float
      - type: object
        extensible: true
      - type: array

  Example:
    type: object
    fields:
      summary:
        type: string
      description:
        type: string
      value:
        type: ref
        spec: Any
      extenralValue:
        type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

  Encoding:
    type: object
    fields:
      contentType:
        type: string
      headers:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Header
            - type: ref
              spec: Reference
      style:
        type: string
      explode:
        type: boolean
      allowReserved:
        type: boolean
    extensible: true
    extensionFieldNamesPattern: ^x-

  Header:
    type: object
    fields:
      description:
        type: string
      required:
        type: boolean
      deprecated:
        type: boolean
      allowEmptyValue:
        type: boolean
      style:
        type: string
      explode:
        type: boolean
      allowReserved:
        type: boolean
      schema:
        type: mixed
        options:
          - type: ref
            spec: Schema
          - type: ref
            spec: Reference
      example:
        type: ref
        spec: Any
      examples:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Example
            - type: ref
              spec: Reference
      content:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: MediaType
    extensible: true
    extensionFieldNamesPattern: ^x-

  Responses:
    type: object
    extensible: true
    fields:
      default:
        type: mixed
        options:
          - type: ref
            spec: Response
          - type: ref
            spec: Reference
    extensionFields:
      type: mixed
      options:
        - type: ref
          spec: Response
        - type: ref
          spec: Reference
    # @todo Add pattern for extension field names (HTTP codes).

  Response:
    type: object
    fields:
      description:
        type: string
      headers:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Header
            - type: ref
              spec: Reference
      content:
        type: object
        extensible: true
        extensionFields:
          type: ref
          spec: MediaType
      links:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Link
            - type: ref
              spec: Reference

  Link:
    type: object
    fields:
      operationRef:
        type: string
      operationId:
        type: string
      parameters:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Any
            - type: string # @todo check {expression} for this option. see if this option should be before Any.
      requestBody:
        type: mixed
        options:
          - type: ref
            spec: Any
          - type: string # @todo check {expression} for this option. see if this option should be before Any.
      description:
        type: string
      server:
        type: ref
        spec: Server
    extensible: true
    extensionFieldNamesPattern: ^x-

  Tag:
    type: object
    fields:
      name:
        type: string
      description:
        type: string
      externalDocs:
        type: ref
        spec: ExternalDocumentation
    extensible: true
    extensionFieldNamesPattern: ^x-

  Components:
    type: object
    fields:
      schemas:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Schema
            - type: ref
              spec: Reference
      responses:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Response
            - type: ref
              spec: Reference
      parameters:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Parameter
            - type: ref
              spec: Reference
      examples:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Example
            - type: ref
              spec: Reference
      requestBodies:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: RequestBody
            - type: ref
              spec: Reference
      headers:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Header
            - type: ref
              spec: Reference
      securitySchemes:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: SecurityScheme
            - type: ref
              spec: Reference
      links:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Link
            - type: ref
              spec: Reference
      callbacks:
        type: object
        extensible: true
        extensionFields:
          type: mixed
          options:
            - type: ref
              spec: Callback
            - type: ref
              spec: Reference
    extensible: true
    extensionFieldNamesPattern: ^x-

  SecurityScheme:
    type: object
    fields:
      type:
        type: string
      description:
        type: string
      name:
        type: string
      in:
        type: string
      scheme:
        type: string
      bearerFormat:
        type: string
      flows:
        type: ref
        spec: OAuthFlows
      openIdConnectUrl:
        type: string

  OAuthFlows:
    type: object
    fields:
      implicit:
        type: ref
        spec: OAuthFlow
      password:
        type: ref
        spec: OAuthFlow
      clientCredentials:
        type: ref
        spec: OAuthFlow
      authorizationCode:
        type: ref
        spec: OAuthFlow
    extensible: true
    extensionFieldNamesPattern: ^x-

  OAuthFlow:
    type: object
    fields:
      authorizationUrl:
        type: string
      tokenUrl:
        type: string
      refreshUrl:
        type: string
      scopes:
        type: object
        extensible: true
        extensionFields:
          type: string
    extensible: true
    extensionFieldNamesPattern: ^x-

# @todo double check schema vs scheme in all the spec.

  SecurityRequirement:
    type: object
    extensible: true
    extensionFields:
      type: array
      items:
        type: string

  XmlObject:
    type: object
    fields:
      name:
        type: string
      namespace:
        type: string
      prefix:
        type: string
      attribute:
        type: boolean
      wrapped:
        type: boolean
    extensible: true
    extensionFieldNamesPattern: ^x-

  Discriminator:
    type: object
    fields:
      propertyName:
        type: string
      mapping:
        type: object
        extensible: true
        extensionFields:
          type: string